# pull official base image
FROM node:latest

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json /app
RUN npm install

# add app
COPY server.js /app

# start app
CMD node server.js
EXPOSE 8080
